sudo: true
language: node_js
notifications:
  email:
    - tjudengfuping@gmail.com
node_js:
  - 9
script:
  - npm run lint
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: V3tfmWJaytF6wn0R6ElaJ4V7j0CX8EHhlvclp38S9DcU+fyqrCUx3OtvBYafEcOmlxaPQprMYD+VRaHMrPlJXrb8yVO62Zg7j42y1v6J8GHOhxgrIcQsyHrEcEfHQMWpwo2aZZ24O5H7S9I6XOGQdvpP21igrMBzYxHj6OPpzC58KQ5a8bn3tbJx56gtwN4U4TzNwZCxLXl3+50YTrLFn+QFMmYEhDGSI77Xv1TXKPL02lBFshXw/Sp+H9kQ+BmbTn761JmdSebjfm0M4hogs+RFDqKr6XsxvtXqDbbTwHd+9nnyv/U08JXyUsACSVhmWh7uVymPc0i2cte/k5yQjK7tuuEja5SkWpwDHU/S1ipgkrjw5Yl7+kOTfEvgCweVMUSP0vFffqY01zLZv6eE6pa9b2eio+FONzde5bsVKtnbSOa15813BEJjfAhh7EVzH7dEPOvHa4GucXR9ekYGLAgsACDrwXc4Qc3AHl80aKD5b+twZsGTR29hTgVSA4JIkb/HvmcCaOhrjMnlBGIgkVS+2wL0ddGRq9QMOCeBtjJolhPXeWZm1+QAviLcP7aCy8eMCljl7GvvO6LYxyC9Yy1XBDfOSE58vWMUZIS9w4Z+I7dWyO1/LQwy6BIZHbZ6WDyfTGoYcZDxeWR7QHCiRix65vjZIl7UCkD6D03DwnE=
  app: antv-bot
  on:
    repo: antvis/antv-bot
env:
  GITHUB_OWNER: antvis
  GITHUB_BOT_NAME: antv-bot
